require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.treesitter"
require "user.autopairs"
require "user.lsp"
require "user.telescope"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.lualine"
require "user.colorizer"
require "user.alpha"
require "user.project"
require "user.impatient"
require "user.neoscroll"
require "user.whichkey"
require "user.gitsigns"
require "user.tabout"
require "user.hop"
require "user.numb"
require "user.lir"
require "user.notify"

vim.cmd 'colorscheme tokyonight'
